name: Manual Newman API Tests CI

on:
  workflow_dispatch:

jobs:
  newman:
    name: Run Newman API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: |
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 & 
          sleep 5

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests with Newman
        run: newman run postman/collection.json
